config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users

  resources :teachers do
    collection do
      get :search
    end
  end

  resources :tutorings, only: [:new, :create]
  resources :users, only: [:show]
  resources :admins, only: [:index, :show]
  resources :experiences, except: [:index, :show]
  resources :services, except: [:index, :show]
  resources :tests, except: [:index]
  resources :reviews, except: [:index]

  get 'landing', to: 'teachers#landing', as: 'teachers_landing'
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  has_many :tutorings
  has_many :teachers
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
  has_many :teachers
  has_many :tutorings
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :teacher
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :teacher
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :topic
  belongs_to :subject

  enum type_tutoring: [ :a_domicilio, :en_lugar_intermedio, :por_skype ]
  enum academ_level: [ :primaria, :bachillerato, :universitario, :postgrado ]
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :topics
  has_many :tutorings
  has_many :services
  has_many :tests
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :user
  belongs_to :city
  belongs_to :country
  has_many :tutorings
  has_many :users, through: :tutorings
  has_many :experiences
  has_many :services
  has_many :tests
  has_many :reviews
  has_many :users, through: :reviews

  validates :phone, :address, :about_me, presence: true
  validates :about_me, length: { in: 50...500 }
  validates :phone, numericality: { only_integer: true }

  enum role: [ :user, :teacher ]

  before_create :set_default_role

  def set_default_role
    self.role = :teacher
  end

  def self.search(params)
    teachers = Service.where(topic_id: params[:topic].to_i) if params[:topic].present?
    teachers = Teacher.where(city_id: params[:city].to_i)
    teachers
  end
end

app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :subject
  belongs_to :topic
  belongs_to :teacher
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :subject
  has_many :tutorings
  has_many :services
  has_many :tests
end

app/models/tutoring.rb
class Tutoring < ActiveRecord::Base
  belongs_to :user
  belongs_to :teacher
  belongs_to :city
  belongs_to :country
  belongs_to :topic
  belongs_to :subject
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :teachers
  has_many :tutorings
  has_many :teachers, through: :tutorings
  has_many :reviews
  has_many :teachers, through: :reviews

  enum role: [ :estudiante, :profesor, :admin ]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render :layout => 'landing'
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/tutorings_helper.rb
module TutoringsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_header.html.erb
<body class="landing-page">
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
          <div class="navbar-header">
              <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a href="/" class="navbar-brand">Tuttores</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <li class="<%= active_class(root_path) %>"><a class="page-scroll" href="/">Home</a></li>
                <!--<li class="<%#= active_class(teachers_path) %>"><%#= link_to 'Listado Profesores', teachers_path, class: "page-scroll"  %></li>-->
                <li class="<%= active_class(new_tutoring_path) %>"><%= link_to 'Solicitar Tutoria', new_tutoring_path, class: "page-scroll" %></li>
                    <% if user_signed_in? %>
                      <!--<li class="<%#= active_class(current_user) %>"><%#= link_to current_user.name, current_user, class: "page-scroll" %></li>-->
                      <li class="<%= active_class(destroy_user_session_path) %>"><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: "page-scroll" %></li>
                    <% else %>
                      <li class="<%= active_class(new_user_session_path) %>"><%= link_to 'Iniciar Sesión', new_user_session_path, class: "page-scroll" %></li>
                      <li class="<%= active_class(new_user_registration_path) %>"><%= link_to 'Registrarse', new_user_registration_path, class: "page-scroll" %></li>
                    <% end %>
                    <% if user_signed_in? && current_user.admin? %>
                      <li class="<%= active_class(admins_path) %>"><%= link_to "Panel", admins_path, class: "page-scroll" %></li>
                    <% end %>
                  <li class="<%= active_class(teachers_landing_path) %>"><%= link_to 'Conviertete en Profesor', teachers_landing_path, class: "navbar-brand"  %></li>
              </ul>
          </div>
      </div>
  </nav>


  <header id="page-top">
      <%= render 'welcome/alerts' %>
      <div class="container">
          <div class="heading">
              <h1>
                  Clases Particulares de Matemáticas, Física y Química
              </h1>
              <span>Contamos con un selecto grupo de Profesores Particulares en Medellin y Bogotá</span>
              <p class="small">
                  Puedes solicitar una clase de Matemáticas, Física o Química con el profesor de tu preferencia, según tus necesidades y presupuesto. Explora todos los profesores disponibles.
              </p>
              <%#= link_to 'Ver Profesores', teachers_path, class: "btn btn-success btn-sm"  %>
          </div>
      </div>
  </header>

app/views/welcome/index.html.erb
<%= render 'welcome/header' %>

  <section>
      <div class="container">
      <div class="row">
          <div class="col-md-4">
              <h4>Listado de Profesores</h4>
              <p>Tenemos un amplio abanico de profesores particulares en la ciudad de Medellín y Bogotá. Usted puede ver el perfil del profesor, la experiencia, los estudios y demás. podrá ver también su Rating</p>
              <p><%= link_to 'Listado Profesores', teachers_path, class: "navy-link btn btn-sm" %></p>
          </div>
          <div class="col-md-4">
              <h4>Solicitar Tutoria</h4>
              <p>Usted podrá solicitar una tutoria con alguno de nuestros profesores, desde una hora (algunos profesores exigen mínimo 2 horas), y seleccionar el lugar que desea para la clase. </p>
              <p><%= link_to 'Solicitar Tutoria', new_tutoring_path, class: "navy-link btn btn-sm" %></p>
          </div>
          <div class="col-md-4">
              <h4>Calidad de los Profesores</h4>
              <p>Los profesores que hacen parte de nuestra plataforma han pasado por un proceso de verificación de conocimientos y de Hoja de Vida. Igualmente usted siempre podrá calificarlos en nuestra plataforma</p>
              <p><%= link_to 'Listado Profesores', teachers_path, class: "navy-link btn btn-sm" %></p>
          </div>
      </div>
      </div>
  </section>

  <section id="features" class="bg-light">
      <div class="container">
          <div class="row">
              <div class="col-md-6 col-md-offset-3 text-center">
                  <h2><span class="text-success">Características </span>que nos hacen diferentes</h2>
                  <p>
                      Existen diferentes espacios donde usted puede ponerse en contacto con profesores particulares, pero con Tuttores.co usted podrá beneficiarse de lo siguiente:
                  </p>
              </div>
          </div>
          <div class="row m-t-lg">
              <div class="col-md-4 col-md-offset-2">
                  <strong>TutorRating*</strong>
                  <p>Es un sistema de calificaciones que usamos en el cual vamos "Rankeando" los profesores segun las calificaciones que le otorgan los alumnos. A más y mejores calificaciones, mayor será el ranking de ese profesor. </p>
              </div>
              <div class="col-md-4">
                  <strong>Test de Calificación.</strong>
                  <p>Cuando un profesor se registra en nuestra plataforma, nosotros validamos sus conocimientos y su Hoja de Vida, por medio de unos Test internos, los cuales también posicionan y "Rankean" a los profesores. </p>
              </div>
          </div>
          <div class="row m-t-lg">
              <div class="col-md-4 col-md-offset-2">
                  <strong>Contacto Directo.</strong>
                  <p>En nuestra plataforma no hay intermediarios. Usted se contacta directamente con el profesor que le llame la atención según sus propios criterios, como la tarifa por hora, el Rating, la experiencia y el conocimiento, etc.  </p>
              </div>
              <div class="col-md-4">
                  <strong>Múltiples Opciones.</strong>
                  <p>Con más de 100 profesores, usted tendrá la posibilidad de elegir al que mas se acomode a sus necesidades. No será necesario conformarse, usted podrá elegir entre los mejores profesores particulares en cada rama</p>
              </div>
          </div>
      </div>
  </section>

  <section id="team">
      <div class="container">
          <div class="row text-center">
              <div class="col-md-6 col-md-offset-3">
                  <h2><span class="text-success">Tutor</span>Rating</h2>
                  <p>
                      Es un sistema de calificaciones que usamos en el cual vamos "Rankeando" los profesores segun las calificaciones que le otorgan los alumnos. A más y mejores calificaciones, mayor será el ranking de ese profesor. Estos son los profesores mejor "Rankeados" en nuestra plataforma
                  </p>
              </div>
          </div>
      </div>
  </section>

  <!-- Local script for menu handle -->
  <!-- It can be also directive -->
  <script>
      $(document).ready(function () {

          // Page scrolling feature
          $('a.page-scroll').bind('click', function(event) {
              var link = $(this);
              $('html, body').stop().animate({
                  scrollTop: $(link.attr('href')).offset().top - 50
              }, 500);
              event.preventDefault();
          });

          $('body').scrollspy({
              target: '.navbar-fixed-top',
              offset: 80
          });

      });
  </script>
</body>