config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users

  resources :teachers do
    collection do
      get :search
    end
  end

  resources :tutorings, only: [:new, :create]
  resources :users, only: [:show]
  resources :admins, only: [:index, :show]
  resources :experiences, except: [:index, :show]
  resources :services, except: [:index, :show]
  resources :tests, except: [:index]
  resources :reviews, except: [:index]

  get 'landing', to: 'teachers#landing', as: 'teachers_landing'
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  has_many :tutorings
  has_many :teachers
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
  has_many :teachers
  has_many :tutorings
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :teacher
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :teacher
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :topic
  belongs_to :subject

  enum type_tutoring: [ :a_domicilio, :en_lugar_intermedio, :por_skype ]
  enum academ_level: [ :primaria, :bachillerato, :universitario, :postgrado ]
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :topics
  has_many :tutorings
  has_many :services
  has_many :tests
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :user
  belongs_to :city
  belongs_to :country
  has_many :tutorings
  has_many :users, through: :tutorings
  has_many :experiences
  has_many :services
  has_many :tests
  has_many :reviews
  has_many :users, through: :reviews

  validates :phone, :address, :about_me, presence: true
  validates :about_me, length: { in: 50...500 }
  validates :phone, numericality: { only_integer: true }

  enum role: [ :user, :teacher ]

  before_create :set_default_role

  def set_default_role
    self.role = :teacher
  end

  def self.search(params)
    teachers = Service.where(topic_id: params[:topic].to_i) if params[:topic].present?
    teachers = Teacher.where(city_id: params[:city].to_i)
    teachers
  end
end

app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :subject
  belongs_to :topic
  belongs_to :teacher
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :subject
  has_many :tutorings
  has_many :services
  has_many :tests
end

app/models/tutoring.rb
class Tutoring < ActiveRecord::Base
  belongs_to :user
  belongs_to :teacher
  belongs_to :city
  belongs_to :country
  belongs_to :topic
  belongs_to :subject
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :teachers
  has_many :tutorings
  has_many :teachers, through: :tutorings
  has_many :reviews
  has_many :teachers, through: :reviews

  enum role: [ :estudiante, :profesor, :admin ]
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!, except: [ :landing, :index ]
  before_action :is_teacher?, except: [ :landing, :index, :show, :search ]
  before_filter :validate_user, only: [:edit, :update, :destroy]

  def landing
    render :layout => 'landing'
  end

  def index
    @teachers = Teacher.all.order(created_at: :desc)
    render :layout => 'landing'
  end

  def show
    @teacher = Teacher.find(params[:id])
    @tutorings = @teacher.tutorings
    @tutoring = Tutoring.new

  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.user = current_user

    if @teacher.save
      flash[:notice] = 'El profesor ha sido creado con éxito'
      redirect_to new_experience_path
    else
      flash[:alert] = 'Algo fallo, el profesor no ha sido creado con éxito'
      render :new
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])

    if @teacher.update(teacher_params)
      flash[:notice] = 'El profesor ha sido actualizado con éxito'
      redirect_to teachers_path
    else
      flash[:alert] = 'Algo fallo, el profesor no ha sido actualizado con éxito'
      render :edit
    end
  end

  def destroy
    @teacher = Teacher.find(params[:id])

    @teacher.destroy
    flash[:notice] = 'El profesor ha sido eliminado con éxito'
    redirect_to teachers_path
  end

  def search
    if params[:city].blank? && params[:topic].blank?
      @teachers = Teacher.all.order(created_at: :desc)
    else
      @teachers = Teacher.search(params)
    end
  end

  private
    def teacher_params
      params.require(:teacher).permit(:phone, :user_id, :image_url, :verify_bgd_check, :complete_exam, :about_me, :address, :verify_phone, :role, :country_id, :city_id )
    end

    def is_teacher?
      unless current_user.profesor?
       flash[:alert] = 'No tienes permisos para acceder a esta ruta, debes estar registrado como profesor'
       redirect_to edit_user_registration_path
      end
    end

    def validate_user
      @teacher = Teacher.find(params[:id])
      redirect_to root_path unless current_user.id.to_s == @teacher.user_id.to_s
      flash[:alert] = 'No tienes permisos para acceder a esta ruta'
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)

    if @test.save
      flash[:notice] = 'El test ha sido enviado con éxito'
      redirect_to teachers_landing_path
    else
      flash[:alert] = 'Algo fallo, el test no ha sido enviado con éxito'
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private
    def test_params
      params.require(:test).permit(:questions, :answers, :topic_id, :result, :teacher_id, :subject_id )
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/tutorings_helper.rb
module TutoringsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/teachers/_alerts.html.erb
<div class="alerts text-center">
  <% if flash[:notice] %>
  <div class="col-lg-12">
    <br>
      <div class="hpanel alert alert-success">
          <div>
              <p style="color:black">
                  <%= flash[:notice] %>
              </p>
          </div>
      </div>
  </div>
  <% elsif flash[:alert] %>
  <div class="col-lg-12">
    <br>
      <div class="hpanel alert alert-danger">
          <div>
              <p style="color:black">
                  <%= flash[:alert] %>
              </p>
          </div>
      </div>
  </div>
  <% end %>
</div>

app/views/teachers/_form.html.erb
<%= form_for @teacher do |f| %>
  <% if @teacher.errors.any? %>
    <div id="errors_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% @teacher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center m-b-md" id="wizardControl">

      <a class="btn btn-primary" href="" data-toggle="tab">Paso 1 - Información Básica</a>
      <a class="btn btn-default" href="" data-toggle="tab">Paso 2 - Experiencia</a>
      <a class="btn btn-default" href="" data-toggle="tab">Paso 3 - Servicio a Ofrecer</a>

  </div>

  <div class="tab-content">
  <div id="step1" class="p-m tab-pane active">

      <div class="row">
          <div class="col-lg-12">
              <div class="row">

                <div class="form-group col-lg-12">
                  <%= f.label :country_id, 'Pais:' %>
                  <%= f.collection_select :country_id, Country.order(:name), :id, :name, include_blank: true, class: 'form-control' %>
                </div>

                <div class="form-group col-lg-12">
                  <%= f.label :city_id, 'Ciudad:' %>
                  <%= f.grouped_collection_select :city_id, Country.order(:name), :cities, :name, :id, :name, include_blank: true, class: 'form-control' %>
                </div>

                <div class="form-group col-lg-12">
                  <%= f.label :phone, 'Telefono:' %>
                  <%= f.text_field :phone, required: true, class: 'form-control', placeholder: "Ingrese su numero de teléfono" %>
                </div>

                <div class="form-group col-lg-12">
                  <%= f.label :address, 'Dirección de Residencia:' %>
                  <%= f.text_field :address, required: true, class: 'form-control', placeholder: "Ingrese su dirección de residencia" %>
                </div>

                <div class="form-group col-lg-12">
                  <%= f.label :about_me, 'Sobre Mi:' %>
                  <%= f.text_area :about_me, rows: 10, required: true, class: 'form-control', placeholder: "Ingrese una descripción sobre usted" %>
                </div>

              </div>
          </div>
      </div>

      <div class="text-right m-t-xs">
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :teacher_id, value: @teacher.id %>
        <%= link_to 'Volver', teachers_path, class: 'btn btn-danger' %>
        <%= f.submit "#{action} Profesor", class: 'btn btn-success' %>
      </div>

  </div>

</div>
<% end %>

app/views/teachers/_header.html.erb
<body class="landing-page">

  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
          <div class="navbar-header">
              <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a href="/" class="navbar-brand">Tuttores</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                  <li class="<%= active_class(root_path) %>"><a class="page-scroll" href="/">Home</a></li>
                  <!--<li class="<%#= active_class(teachers_path) %>"><%#= link_to 'Listado Profesores', teachers_path, class: "page-scroll"  %></li>-->
                  <li class="<%= active_class(new_tutoring_path) %>"><%= link_to 'Solicitar Tutoria', new_tutoring_path, class: "page-scroll" %></li>
                    <% if user_signed_in? %>
                      <!--<li class="<%#= active_class(current_user) %>"><%#= link_to current_user.name, current_user, class: "page-scroll" %></li>-->
                      <li class="<%= active_class(destroy_user_session_path) %>"><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: "page-scroll" %></li>
                    <% else %>
                      <li class="<%= active_class(new_user_session_path) %>"><%= link_to 'Iniciar Sesión', new_user_session_path, class: "page-scroll" %></li>
                      <li class="<%= active_class(new_user_registration_path) %>"><%= link_to 'Registrarse', new_user_registration_path, class: "page-scroll" %></li>
                    <% end %>
                    <% if user_signed_in? && current_user.admin? %>
                      <li class="<%= active_class(admins_path) %>"><%= link_to "Panel", admins_path, class: "page-scroll" %></li>
                    <% end %>
                  <li class="<%= active_class(new_teacher_path) %>"><%= link_to 'Registro como Profesor', new_teacher_path, class: "navbar-brand"  %></li>
              </ul>
          </div>
      </div>
  </nav>


  <header id="page-top">
      <%= render 'welcome/alerts' %>
      <div class="container">
          <div class="heading">
              <h1>
                  Registrate como profesor
              </h1>
              <span>Contamos con un selecto grupo de Profesores Particulares en Medellin y Bogotá</span>
              <p class="small">
                  Puedes realizar hasta cientos de clases de Matemáticas, Física o Química.
              </p>
              <%#= link_to 'Ver Profesores', teachers_path, class: "btn btn-success btn-sm"  %>
          </div>
      </div>
  </header>

app/views/teachers/_header_app.html.erb
<body class="landing-page hide-sidebar">

<!-- Header -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">Tuttores</a>
            <div class="brand-desc">
                Profesores Particulares
            </div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              <li class="<%= active_class(root_path) %>"><a class="page-scroll" href="/">Home</a></li>
              <li class="<%= active_class(teachers_path) %>"><%= link_to 'Listado Profesores', teachers_path, class: "page-scroll"  %></li>
              <li class="<%= active_class(new_tutoring_path) %>"><%= link_to 'Solicitar Tutoria', new_tutoring_path, class: "page-scroll" %></li>
                <% if user_signed_in? %>
                  <!--<li class="<%#= active_class(current_user) %>"><%#= link_to current_user.name, current_user, class: "page-scroll" %></li>-->
                  <li class="<%= active_class(destroy_user_session_path) %>"><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: "page-scroll" %></li>
                <% else %>
                  <li class="<%= active_class(new_user_session_path) %>"><%= link_to 'Iniciar Sesión', new_user_session_path, class: "page-scroll" %></li>
                  <li class="<%= active_class(new_user_registration_path) %>"><%= link_to 'Registrarse', new_user_registration_path, class: "page-scroll" %></li>
                <% end %>
                <% if user_signed_in? && current_user.admin? %>
                  <li class="<%= active_class(admins_path) %>"><%= link_to "Panel", admins_path, class: "page-scroll" %></li>
                <% end %>
              <li class="<%= active_class(new_teacher_path) %>"><%= link_to 'Registro como Profesor', new_teacher_path, class: "navbar-brand"  %></li>
          </ul>
        </div>
    </div>
</nav>

app/views/teachers/_teacher_listings.html.erb
<div class="content animate-panel">

  <div class="row">
      <div class="col-md-3">
          <div class="hpanel">
              <div class="panel-body">
                  <div class="m-b-md">
                      <h4>
                          Filters
                      </h4>
                      <small>
                          Filter your project basend on diferent options below.
                      </small>
                  </div>

                  <%= form_tag search_teachers_path, method: :get do |f| %>
                  <div class="form-group">
                      <label class="control-label">Ciudad:</label>
                      <div class="input-group">
                          <%= select_tag :city, content_tag(:option,'Selecciona...',:value=>"")+options_from_collection_for_select(City.all, :id, :name), class: "form-control m-b" %>
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="control-label">Materia:</label>
                      <div class="input-group">
                          <%= select_tag :topic, content_tag(:option,'Selecciona...',:value=>"")+options_from_collection_for_select(Topic.all, :id, :name), class: "form-control m-b" %>
                      </div>
                  </div>
                  <%= submit_tag "Buscar", class: "btn btn-success btn-block" %>
                  <% end %>
              </div>
          </div>
      </div>
      <div class="col-md-9">
          <div class="row">

            <% @teachers.each do |teacher| %>
            <div class="col-lg-4">
                <div class="hpanel hgreen contact-panel">
                    <%= link_to teacher do %>
                    <div class="panel-body">
                        <span class="label label-success pull-right">NEW</span>
                        <img alt="logo" class="img-circle m-b" src="/assets/profile.jpg">
                        <h3> Bradly Danforth </h3>
                        <div class="text-muted font-bold m-b-xs">California, LA</div>
                        <p>
                            <%= teacher.about_me %>
                        </p>
                    </div>
                    <% end %>
                    <div class="panel-footer contact-footer">
                        <div class="row">
                            <div class="col-md-4 border-right"> <div class="contact-stat"><span>Projects: </span> <strong>200</strong></div> </div>
                            <div class="col-md-4 border-right"> <div class="contact-stat"><span>Messages: </span> <strong>300</strong></div> </div>
                            <div class="col-md-4"> <div class="contact-stat"><span>Views: </span> <strong>400</strong></div> </div>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
          </div>
      </div>
  </div>
</div>



    <!-- Right sidebar -->
    <div id="right-sidebar" class="animated fadeInRight">

        <div class="p-m">
            <button id="sidebar-close" class="right-sidebar-toggle sidebar-button btn btn-default m-b-md"><i class="pe pe-7s-close"></i>
            </button>
            <div>
                <span class="font-bold no-margins"> Analytics </span>
                <br>
                <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.</small>
            </div>
            <div class="row m-t-sm m-b-sm">
                <div class="col-lg-6">
                    <h3 class="no-margins font-extra-bold text-success">300,102</h3>

                    <div class="font-bold">98% <i class="fa fa-level-up text-success"></i></div>
                </div>
                <div class="col-lg-6">
                    <h3 class="no-margins font-extra-bold text-success">280,200</h3>

                    <div class="font-bold">98% <i class="fa fa-level-up text-success"></i></div>
                </div>
            </div>
            <div class="progress m-t-xs full progress-small">
                <div style="width: 25%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="25" role="progressbar"
                     class=" progress-bar progress-bar-success">
                    <span class="sr-only">35% Complete (success)</span>
                </div>
            </div>
        </div>
        <div class="p-m bg-light border-bottom border-top">
            <span class="font-bold no-margins"> Social talks </span>
            <br>
            <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.</small>
            <div class="m-t-md">
                <div class="social-talk">
                    <div class="media social-profile clearfix">
                        <a class="pull-left">
                            <img src="/assets/a1.jpg" alt="profile-picture">
                        </a>

                        <div class="media-body">
                            <span class="font-bold">John Novak</span>
                            <small class="text-muted">21.03.2015</small>
                            <div class="social-content small">
                                Injected humour, or randomised words which don't look even slightly believable.
                            </div>
                        </div>
                    </div>
                </div>
                <div class="social-talk">
                    <div class="media social-profile clearfix">
                        <a class="pull-left">
                            <img src="/assets/a3.jpg" alt="profile-picture">
                        </a>

                        <div class="media-body">
                            <span class="font-bold">Mark Smith</span>
                            <small class="text-muted">14.04.2015</small>
                            <div class="social-content">
                                Many desktop publishing packages and web page editors.
                            </div>
                        </div>
                    </div>
                </div>
                <div class="social-talk">
                    <div class="media social-profile clearfix">
                        <a class="pull-left">
                            <img src="/assets/a4.jpg" alt="profile-picture">
                        </a>

                        <div class="media-body">
                            <span class="font-bold">Marica Morgan</span>
                            <small class="text-muted">21.03.2015</small>

                            <div class="social-content">
                                There are many variations of passages of Lorem Ipsum available, but the majority have
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="p-m">
            <span class="font-bold no-margins"> Sales in last week </span>
            <div class="m-t-xs">
                <div class="row">
                    <div class="col-xs-6">
                        <small>Today</small>
                        <h4 class="m-t-xs">$170,20 <i class="fa fa-level-up text-success"></i></h4>
                    </div>
                    <div class="col-xs-6">
                        <small>Last week</small>
                        <h4 class="m-t-xs">$580,90 <i class="fa fa-level-up text-success"></i></h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        <small>Today</small>
                        <h4 class="m-t-xs">$620,20 <i class="fa fa-level-up text-success"></i></h4>
                    </div>
                    <div class="col-xs-6">
                        <small>Last week</small>
                        <h4 class="m-t-xs">$140,70 <i class="fa fa-level-up text-success"></i></h4>
                    </div>
                </div>
            </div>
            <small> Lorem Ipsum is simply dummy text of the printing simply all dummy text.
                Many desktop publishing packages and web page editors.
            </small>
        </div>

    </div>

    <!-- Footer-->
    <footer class="footer">
        <span class="pull-right">
            Example text
        </span>
        Company 2015-2020
    </footer>

app/views/teachers/edit.html.erb
<body class="blank">

<div class="color-line"></div>
<div class="back-link">
    <a href="/" class="btn btn-primary">Volver al Home</a>
</div>
<div class="register-container">
    <div class="row">
      <div class="col-lg-12">
          <div class="hpanel">
              <div class="panel-heading">
                  <div class="panel-tools">
                      <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                      <a class="closebox"><i class="fa fa-times"></i></a>
                  </div>
              </div>
              <div class="panel-body">
                <%= render 'form', action: 'Editar' %>
                  <div class="m-t-md">
                      <p>
                      </p>
                  </div>
              </div>
          </div>
      </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
        </div>
    </div>
</div>
<br><br><br>
  <script>
      $(function(){

          $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
              $('a[data-toggle="tab"]').removeClass('btn-primary');
              $('a[data-toggle="tab"]').addClass('btn-default');
              $(this).removeClass('btn-default');
              $(this).addClass('btn-primary');
          })

          $('.next').click(function(){
              var nextId = $(this).parents('.tab-pane').next().attr("id");
              $('[href=#'+nextId+']').tab('show');
          })

          $('.prev').click(function(){
              var prevId = $(this).parents('.tab-pane').prev().attr("id");
              $('[href=#'+prevId+']').tab('show');
          })

          $('.submitWizard').click(function(){

              var approve = $(".approveCheck").is(':checked');
              if(approve) {
                  // Got to step 1
                  $('[href=#step1]').tab('show');

                  // Serialize data to post method
                  var datastring = $("#simpleForm").serialize();

                  // Show notification
                  swal({
                      title: "Thank you!",
                      text: "You approved our example form!",
                      type: "success"
                  });
  //            Example code for post form
  //            $.ajax({
  //                type: "POST",
  //                url: "your_link.php",
  //                data: datastring,
  //                success: function(data) {
  //                    // Notification
  //                }
  //            });
              } else {
                  // Show notification
                  swal({
                      title: "Error!",
                      text: "You have to approve form checkbox.",
                      type: "error"
                  });
              }
          })
      });
  </script>
</body>

app/views/teachers/index.html.erb
<%= render 'teachers/header_app' %>

  <!-- Main Wrapper -->
  <div id="wrapper">

  <br><br><br>
  <%= render 'teachers/teacher_listings' %>

  </div>

</body>

app/views/teachers/landing.html.erb
<%= render 'teachers/header' %>

<section>
    <div class="container">
    <div class="row">
        <div class="col-md-4">
            <h4>Listado de Profesores</h4>
            <p>Tenemos un amplio abanico de profesores particulares en la ciudad de Medellín y Bogotá. Usted puede ver el perfil del profesor, la experiencia, los estudios y demás. podrá ver también su Rating</p>
            <p><%= link_to 'Listado Profesores', teachers_path, class: "navy-link btn btn-sm" %></p>
        </div>
        <div class="col-md-4">
            <h4>Solicitar Tutoria</h4>
            <p>Usted podrá solicitar una tutoria con alguno de nuestros profesores, desde una hora (algunos profesores exigen mínimo 2 horas), y seleccionar el lugar que desea para la clase. </p>
            <p><%= link_to 'Solicitar Tutoria', new_tutoring_path, class: "navy-link btn btn-sm" %></p>
        </div>
        <div class="col-md-4">
            <h4>Calidad de los Profesores</h4>
            <p>Los profesores que hacen parte de nuestra plataforma han pasado por un proceso de verificación de conocimientos y de Hoja de Vida. Igualmente usted siempre podrá calificarlos en nuestra plataforma</p>
            <p><%= link_to 'Listado Profesores', teachers_path, class: "navy-link btn btn-sm" %></p>
        </div>
    </div>
    </div>
</section>

<section id="features" class="bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
                <h2><span class="text-success">Características </span>que nos hacen diferentes</h2>
                <p>
                    Existen diferentes espacios donde usted puede ponerse en contacto con profesores particulares, pero con Tuttores.co usted podrá beneficiarse de lo siguiente:
                </p>
            </div>
        </div>
        <div class="row m-t-lg">
            <div class="col-md-4 col-md-offset-2">
                <strong>TutorRating*</strong>
                <p>Es un sistema de calificaciones que usamos en el cual vamos "Rankeando" los profesores segun las calificaciones que le otorgan los alumnos. A más y mejores calificaciones, mayor será el ranking de ese profesor. </p>
            </div>
            <div class="col-md-4">
                <strong>Test de Calificación.</strong>
                <p>Cuando un profesor se registra en nuestra plataforma, nosotros validamos sus conocimientos y su Hoja de Vida, por medio de unos Test internos, los cuales también posicionan y "Rankean" a los profesores. </p>
            </div>
        </div>
        <div class="row m-t-lg">
            <div class="col-md-4 col-md-offset-2">
                <strong>Contacto Directo.</strong>
                <p>En nuestra plataforma no hay intermediarios. Usted se contacta directamente con el profesor que le llame la atención según sus propios criterios, como la tarifa por hora, el Rating, la experiencia y el conocimiento, etc.  </p>
            </div>
            <div class="col-md-4">
                <strong>Múltiples Opciones.</strong>
                <p>Con más de 100 profesores, usted tendrá la posibilidad de elegir al que mas se acomode a sus necesidades. No será necesario conformarse, usted podrá elegir entre los mejores profesores particulares en cada rama</p>
            </div>
        </div>
    </div>
</section>

<section id="team">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-6 col-md-offset-3">
                <h2><span class="text-success">Tutor</span>Rating</h2>
                <p>
                    Es un sistema de calificaciones que usamos en el cual vamos "Rankeando" los profesores segun las calificaciones que le otorgan los alumnos. A más y mejores calificaciones, mayor será el ranking de ese profesor. Estos son los profesores mejor "Rankeados" en nuestra plataforma
                </p>
            </div>
        </div>
    </div>
</section>

<!-- Local script for menu handle -->
<!-- It can be also directive -->
<script>
    $(document).ready(function () {

        // Page scrolling feature
        $('a.page-scroll').bind('click', function(event) {
            var link = $(this);
            $('html, body').stop().animate({
                scrollTop: $(link.attr('href')).offset().top - 50
            }, 500);
            event.preventDefault();
        });

        $('body').scrollspy({
            target: '.navbar-fixed-top',
            offset: 80
        });

    });
</script>
</body>